service framework
s21platform/chat-service pull request #3
Opened 2024-12-12 16:32 UTC by LoskutovDaniil

2024-12-13 15:43 UTC, mikhail-kalugin requested changes

2024-12-13 15:43 UTC, mikhail-kalugin commented on Dockerfile
> +
А из-за чего тут закоменчено?

2024-12-13 15:43 UTC, mikhail-kalugin commented on cmd/service/main.go
> +		log.Printf("failed connection to db: %v", err)
лучше сразу пиши log.Fatalln
он выведет сообщение и сразу завершит программу

2024-12-13 15:43 UTC, mikhail-kalugin commented on .env
> +CHAT_SERVICE_POSTGRES_USER=postgres
По факту, если ты случайно залил .env в пр, то лучше будет закрыть пр и заново запушить, иначе можно по коммитам отыскать этот файл. 
Сейчас давай уже не будем менять, все равно это локальный env

2024-12-13 19:57 UTC, alexseipopov requested changes

2024-12-13 19:57 UTC, alexseipopov commented on .env
> +CHAT_SERVICE_POSTGRES_USER=postgres
но удалить стоит)

2024-12-13 19:57 UTC, alexseipopov commented on Dockerfile
> +RUN apk add --no-cache gcompat
@mikhail-kalugin Миш, а это не библиотечка что только для аватарок нужна?

2024-12-13 19:57 UTC, alexseipopov commented on internal/repository/postgres/repository.go
> +func New(cfg *config.Config) (*Repository, error) {
А зачем мы стали возвращать ошибку. Мы же как раз тут и зафаталимся. Ошибку возвращать не обязательно

2024-12-13 19:57 UTC, alexseipopov commented on cmd/service/main.go
> +		log.Printf("failed connection to db: %v", err)
@LoskutovDaniil @mikhail-kalugin Оставил коммент ниже, но думаю не стоит возвращать ошибку. пусть при ошибке внутри там все и фаталится

2024-12-14 12:31 UTC, mikhail-kalugin commented on .env
> +CHAT_SERVICE_POSTGRES_USER=postgres
Не, удалить-то стоит, да, но в коммитах-то останется

2024-12-14 12:34 UTC, mikhail-kalugin commented on Dockerfile
> +RUN apk add --no-cache gcompat
Не-а, эта, по-моему, для запуска программы на Alpine нужна, а у меня libwebp под аватары используется

2024-12-14 12:35 UTC, mikhail-kalugin commented on cmd/service/main.go
> +		log.Printf("failed connection to db: %v", err)
согласен

2024-12-16 13:50 UTC, mikhail-kalugin requested changes

2024-12-16 13:50 UTC, mikhail-kalugin commented on .gitignore
> +.DS_Store
Давай все же оставим тут файлы
.idea/
.env
docker-compose.yml

2024-12-16 13:50 UTC, mikhail-kalugin commented on Dockerfile
> +#COPY --from=builder /usr/src/service/scripts ./scripts
Давай все же удалим закоменченную часть

2024-12-16 13:50 UTC, mikhail-kalugin commented on internal/repository/postgres/repository.go
> +		//log.Fatalf("failed to connect DB")
Думаю, тут лучше будет оставить просто
fmt.Fatalf("failed to connect to db: %v", err)

2024-12-16 13:51 UTC, mikhail-kalugin commented
Также у тебя не проходит линтеры, как я посмотрел, он не подтягивает chat-proto

Run golangci-lint run
level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for \"github.com/s21platform/chat-proto/chat-proto\""
level=error msg="Running error: can't run linter goanalysis_metalinter\nbuildir: failed to load package : could not load export data: no export data for \"github.com/s21platform/chat-proto/chat-proto\""
Error: Process completed with exit code 3.

2024-12-16 22:00 UTC, mikhail-kalugin approved these changes

2024-12-16 22:50 UTC, alexseipopov approved these changes

2024-12-17 07:50 UTC, merged